### ISSUE TITLE
Add functionality for remote database install

### ISSUE THREAD

**Issue by mrrobot47** [EasyEngine/site-command#10]
The current site-command creates it's own database container and is limited to it only. Need to add the feature to connect to remote databases.

**Comment by mrrobot47** [comment]
Depends on https://github.com/EasyEngine/easyengine/issues/1029. It will be worked upon as soon as this gets merged.

**Comment by kirtangajjar** [comment]
Fixed by https://github.com/EasyEngine/site-command/pull/40
