### ISSUE TITLE
Add site update command

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/site-command#116]
- [x] Upgrade PHP version
- [x] Upgrade to ssl (reverse not supported)
- [x] Upgrade cache (enable/disable)
- [x] Upgrade between site types
  - [ ] Upgrade between WP types - WP subdom, WP subdir

**Comment by mbtamuli** [comment]
## PHP Versions
The PHP docker images will be named like - `easyengine/php5.6:v4.0.0`, `easyengine/php7.0:v4.0.0`, `easyengine/php7.1:v4.0.0`, `easyengine/php7.2:v4.0.0`

- [ ] Take backup of PHP ini files.
- [ ] Check if previous backup of PHP for the requested version exists and restore them.
- [ ] Upgrade `docker-compose.yml` and start new container replacing the old one.

## Upgrade to SSL
Upgrading to SSL would be generally simply requesting the SSL certificates for the site, for example - for `HTML` and `PHP` site types.

For site types where the application is known, example WP site type, we might also need to perform additional steps like - 

- [ ] Search-replace `wp search replace 'http://example.com' 'https://example.com'`

**Comment by mrrobot47** [comment]
A list of possible updates to be supported in v4. 

## SSL update
```bash
ee site update example.com --ssl=le
ee site update example.com --ssl=le --wildcard
```

## PHP version update for Site type PHP and WP
```bash
ee site update example.com --php=5.6
ee site update example.com --php=7.0
ee site update example.com --php=7.1
ee site update example.com --php=7.2
ee site update example.com --php=7.3
```

## Cache update for Site type PHP and WP
```bash
# Non-cache site to cache site
ee site update example.com --cache
ee site update example.com --cache --with-local-redis

# Disabling cache (Scope later)
ee site update example.com --no-cache

# Should future scope include switching between local and global redis cache?
```

## Site Type Updates
```bash
# To Site Type PHP from HTML:
ee site update example.com --type=php
ee site update example.com --type=php --cache
ee site update example.com --type=php --with-db
ee site update example.com --type=php --cache --with-local-redis
ee site update example.com --type=php --with-db --local-db
ee site update example.com --type=php --with-db --local-db --cache --with-local-redis

## To Site Type WP from HTML or PHP:
ee site update example.com --type=wp
ee site update example.com --type=wp --mu=subdir
ee site update example.com --type=wp --mu=subdom
ee site update example.com --type=wp --dbhost=localhost --dbuser=username --dbpass=password
ee site update example.com --type=wp --local-db
ee site update example.com --type=wp --cache
ee site update example.com --type=wp --cache --with-local-redis
```

## Site Type PHP internal
```bash
# without-db site to site with db
ee site update example.com --with-db
ee site update example.com --with-db --local-db

# with-db site to without-db site (Scope later)
ee site update example.com --without-db

# Should future scope include switching between local and global db?
```

## Site Type WP internal
```bash
# Simple WP site to MU
ee site update example.com --mu=subdir
ee site update example.com --mu=subdom

# Should future scope include switching between local and global db?
```

Note: This is not an exhaustive list. Multiple update types can be clubbed together to form numerous amount of permutations and combinations of `ee site update`. For example PHP version change, SSL update and site type update can all be done in a single update command.

@rahul286 @mbtamuli @rahulsprajapati @kirtangajjar Please leave your comments.
