### ISSUE TITLE
Letsencrypt failure should result in rollback. 

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/site-command#117]
Currently, even if EasyEngine fails to request certificates from LetsEncrypt, site creation continues.
Ideally it should fail. Need to update tests after that.

**Comment by mbtamuli** [comment]
Single site SSL
- [ ] Convert warnings thrown while generating SSL certs to exceptions

Wildcard SSL
- [ ] Check before `ee site ssl` is ran that other sites are accessible
- [ ] Delete site if `ee site ssl` fails.
(As mentioned by @kirtangajjar )

**Comment by mrrobot47** [comment]
Closing this as it has been fixed in https://github.com/EasyEngine/site-command/pull/129
