### ISSUE TITLE
Cannot create site -- Home directory already exists (it doesn't)

### ISSUE THREAD

**Issue by b167er** [EasyEngine/site-command#203]
I was creating a site and in the middle of the process I accidentally cancelled it. Now when I go to start the process again, I get the following error:

```
Warning: Could not create user domain.com.au-NtgQJI. Please check logs.
Warning: Initiating clean-up.
PHP Notice:  Undefined index: site_fs_path in phar:///usr/local/bin/ee/vendor/easyengine/site-type-wp/src/WordPress.php on line 965
PHP Notice:  Trying to get property 'cache_host' of non-object in phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/hooks.php on line 56
Site domain.com.au deleted.
```

The thing is, the home directory (in ~/ee-sites) doesn't have a folder for this domain. Actually I have 2 websites running on my server at the moment, and only 1 of those sites has a folder in ~/ee-sites. I'm not sure where the home directory of site #2 is even located. But anyway, site #3, this site above, has no folder created for it in ~/ee-sites but it's still saying that the site exists. How can I remove all traces of this website so I can create it again properly?

**Comment by b167er** [comment]
Uninstalled EE and re-installed it. Still getting the same error. Cannot create this site with this domain again.

**Comment by mbtamuli** [comment]
You might have installed an older version and then proceeded to replace the phar manually, as this path is not being used now - `~/ee-sites`.

If you want to start afresh, please run the following commands
**Warning: This will delete all EasyEngine sites and their data**
```
rm -rf /opt/easyengine ~/ee-sites ~/.ee4 ~/.ee
wget -O /usr/local/bin/ee https://raw.githubusercontent.com/EasyEngine/easyengine-builds/master/phar/easyengine.phar
chmod +x /usr/local/bin/ee
```

Moving forward from [v4 RC1](https://easyengine.io/blog/easyengine-v4-first-release-candidate/), you can run ```ee cli update``` to safely migrate from one version to the next.

**Comment by mrrobot47** [comment]
Closing this issue as it seems to be resolved. This issue will not be faced in stable version or it's updates.
