### ISSUE TITLE
CloudFlare SSL verification not working

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/site-command#287]
If we follow the [steps given on the blog](https://easyengine.io/blog/easyengine-v4-0-7-4-0-9-released/), Cloudflare integration does not work as intended and keeps failing every time.

**Comment by mrrobot47** [comment]
Cloudflare integration is working. There is only one issue currently, if there are more than 20 zones in cloudflare account then the api fetches only the first twenty by default. The [php-sdk api](https://github.com/cloudflare/cloudflare-php) lacks documentation conpletely. As, well as the [functions](https://github.com/cloudflare/cloudflare-php/blob/4694904b38fdf5f251559a473cecf77a63cf9202/src/Endpoints/Zones.php#L61) do not contain comments. So, the direction to traverse records or navigation to next page via api call is ambigous.

Can update the current implemetation to have a very high number of zones per page to overcome the issue temporarily, till the proper documentation in the sdk is released.
