### ISSUE TITLE
Show message when www redirections are not added

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/site-command#307]
EasyEngine adds www redirections(`www.example.com` -> `example.com` or vice-versa) only if it finds that domain with www is pointed to the server. The reason for doing so is that to add https redirect from `www.example.com -> example.com`, we need a cert that is valid for both domains `www.example.com` and `example.com`. And to get that certificate, we need to ensure www is pointed to the server.

This leads to confusion among users who find that sometimes the redirection file is added, while sometimes it is not - https://community.easyengine.io/t/ee-site-create-503-service-temporarily-unavailable/12032

Solution to this issue is:
1. Always add HTTP www redirection
2. If the site has SSL and www domain is pointed, add https www redirection
3. If the site has SSL and www domain is not pointed, show a message on the user's screen that https redirection is not added as the domain is not pointed. Also, add a similar message as comment in the redirection config file.

**Comment by gingerbeardman** [comment]
Dupe #232

**Comment by kirtangajjar** [comment]
Thanks, @gingerbeardman. I liked the description of this issue better so copy-pasted it to the old issue and now closing this one.
