### ISSUE TITLE
Can't connect to MySQL server on 'db' (111 "Connection refused") 

### ISSUE THREAD

**Issue by rahulsprajapati** [EasyEngine/site-command#33]
Getting this issue when creating a site.
```
Debug: COMMAND: docker-compose exec --user='www-data' php wp config create --dbuser='wordpress' --dbname='rahul_test4_local' --dbpass='dbpass' --dbhost='db'  --dbcharset=utf8 (33.629s)
Debug: STDOUT: ERROR 2003 (HY000): Can't connect to MySQL server on 'db' (111 "Connection refused")
```

Seem like the mysql/db service is not available or properly running at the time of site config create. 

Adding [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck) seems to be working for me which I suppose used to create docker container with making sure the "docker-compose up" command runs successfully after the health check pass else it will fail and then we will revert site operation.

Add following healthcheck in db service. ref: https://docs.docker.com/compose/compose-file/#healthcheck

```
healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
```

**Comment by mrrobot47** [comment]
Merged in #34. Will be merged in master for beta2 release.
