### ISSUE TITLE
Add confirmation to the delete commands

### ISSUE THREAD

**Issue by renatonascalves** [EasyEngine/site-command#50]
In the WP CLI world, commands that delete something usually come with a confirmation flag.

I noticed now that the `ee site delete` command has this warning:
> Warning: Doesn't ask for confirmation

I'd recommend adding the confirmation flag. As it is a best practice so that the person is aware and confirm the action he/she is about to take.

**Comment by rahul286** [comment]
Yep. There should be a confirmation and an optional flag. If flag is passed on command-line, confirmation can be skipped.
