### ISSUE TITLE
Allow provision for wildcard certificate for all site-types

### ISSUE THREAD

**Issue by mrrobot47** [EasyEngine/site-command#77]
Currently, EasyEngine only issues a wildcard certificate for `subdomain` multisite type. There should be a provision to allow the generation of wildcard certificate for any site-type. This would be helpful when someone has to create multiple sub-sites of the same, then it would be very simple to reuse the wildcard certificate instead of generating a new one every time. Also, it will ease the maintenance.

```bash
ee site create example.com --le=wildcard
ee site create one.example.com --le # will use the above wildcard domain
ee site create two.example.com --le # will use the above wildcard domain
```

**Comment by rahul286** [comment]
I think we better use separate `--wildcard` flag. 

Any SSL certificate provider can provision a wildcard certificate.

The `--wildcard` flag can have following possible values.

1. **`auto`** - _default_ value, if no value is provided. Behavior is dependent on context. 
- If the domain is a top-level domain, then create a wildcard certificate making _this_ domain parent. Behaves like `--wildcard=parent`. 
- If this (sub)domain already has an upper-level domain with a wildcard certificate, then use parent domain's certificate. Behaves like `--wildcard=child`. 
2. **`parent`** - set current domain/subdomain as top-level parent for all subdomains/sub-subdomains under it.
3. ** `child`** - use parent/grandparent domain's wildcard SSL.
4. **`ignore`** - ignore wildcard certificate even if parent domin has one and start a new certificate.

Use Cases
=========

1. `ee site create example.com --le --wildcard` will generate a wildcard SSL for entire domain.
2.  Next `ee site create food.example.com --le` and `ee site create sports.example.com --le` will create sites where wildcard cert by `example.com` will be used.
3. Then `ee site create store.example.com --le --wildcard=ignore` will be used to generate separate SSL cert for `store.example.com`. There are many reasons to do that such as store.example.com is hosted on another server, or it needs a paid green-bar EV type of certificate.


Examples
==========

```
## set wildcard cert for *.example.com
ee site create example.com --le --wildcard

## use wildcard cert created for *.example.com
ee site create one.example.com --le 
ee site create two.example.com --le --wildcard 
ee site create aplha.one.example.com --le --wildcard=auto
ee site create mars.aplha.one.example.com --le --wildcard=child

## ignore wildcard certificate of parent/grandparent (if present)
## following will get foo.example.com it's own certificate
ee site create mars.aplha.one.example.com --le  --wildcard=ignore

## issue wildcard certificate for section.example.com and all domains under it
ee site create section.example.com --le --wildcard=parent

## use wildcard cert created for *.section.example.com
ee site create sports.section.example.com --le 
ee site create food.section.example.com --le --wildcard 
```

**Comment by mbtamuli** [comment]
@rahul286 I agree with almost all of it.

> Then ee site create store.example.com --le --wildcard=ignore will be used to generate separate SSL cert for store.example.com. There are many reasons to do that such as store.example.com is hosted on another server, or it needs a paid green-bar EV type of certificate.

What about this? When people have certificates they get from another Certificate Authority will the `--le` flag still make sense?

**Comment by kirtangajjar** [comment]
> I think we better use separate --wildcard flag.
> Any SSL certificate provider can provision a wildcard certificate.

On a similar note, how about renaming `--le` to `--ssl` 🤔

**Comment by rahul286** [comment]
> What about this? When people have certificates they get from another Certificate Authority will the --le flag still make sense?

No. 

1. What options `--le` flag have?
2. How can EE help for custom `SSL` setup? Is it a good idea to generate a self-signed certificate and then upgrade it to a third-party one?

**Comment by rahul286** [comment]
> On a similar note, how about renaming --le to --ssl 🤔

Depends on what options `--le` has. Hence asked about it. ☝️ 

We may replace `--le` with `--ssl` and have extra options such as:

1. **`le`** _default_ to LetsEncrypt.
2. **`ss`** generate a self-signed certificate 
3. **`csr`** create a private key and [CSR - certificate signing request](https://en.wikipedia.org/wiki/Certificate_signing_request). The sysadmin will send CSR to SSL provider to obtain a paid SSL!

In a database table, we can have two columns named `ssl` and `wildcard` which together handles all possible combination.

**Comment by rahul286** [comment]
Good reading https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs

**Comment by kirtangajjar** [comment]
> `le` default to LetsEncrypt.
> `ss` generate a self-signed certificate

We can call it `ca` and default it to `letsencrypt`(or `le`). If they want self sign certificate, they can set it to `ss`

i.e. `ee site create --ssl --ca=ss` or `ee site create --ssl --ca=self-signed`

**Comment by mbtamuli** [comment]
@rahul286 I missed this section from your example.
```
## use wildcard cert created for *.example.com
ee site create one.example.com --le 
ee site create two.example.com --le --wildcard 
ee site create aplha.one.example.com --le --wildcard=auto
ee site create mars.aplha.one.example.com --le --wildcard=child
```

Actually this is incorrect as cert for *.example.com will not be valid for aplha.one.example.com or mars.aplha.one.example.com.

**Comment by rahul286** [comment]
@mbtamuli is this LetsEncrypt limitation or SSL in general?

DNS system allows `aplha.one.example.com` or `mars.aplha.one.example.com` to resolve to A/CNAME value set for `*.example.com`.

**Comment by mbtamuli** [comment]
Even if DNS might allow it, the certificate rules are more complex as what the RFC says and what the browsers implement don't match completely. 

From what I could gather from multiple sources, ***.example.com** won't work for **mars.aplha.one.example.com**.

In your example scenario,
1. For **aplha.one.example.com** 
You need either ***.one.example.com**(wildcard) or **alpha.one.example.com**(single)

2. For **mars.aplha.one.example.com** 
You need either ***.alpha.one.example.com**(wildcard) or **mars.alpha.one.example.com**(single)

So if you want to issue wildcard certificates only. To completely cover all the URLs in your scenario, you have to have the mentioned subdomains with wildcard as *alternate name* in the SAN certificate that is created.

So the final certificate for your example scenario will be for **example.com** with alternate names including ***.example.com**, ***.one.example.com** and ***.alpha.one.example.com**.

More details
1. https://community.letsencrypt.org/t/create-wild-card-certs-for-several-subdomains-pointing-to-different-servers/54541
2. https://security.stackexchange.com/questions/10538/what-certificates-are-needed-for-multi-level-subdomains

**Comment by rahul286** [comment]
> Even if DNS might allow

DNS definitely allows it.

> Re: multi-level wildcard and SSL

Let's implement keeping in mind limitation. 

So assuming wildcard SSL exist for *.example.com, _which doesn't matter anyway_, following commands will 

generate a single domain normal cert for **aplha.one.example.com**
```ee site create aplha.one.example.com --le```

uses wildcard cert created for ***.one.example.com**, otherwise request a new wildcard cert for ***.aplha.one.example.com**
```ee site create aplha.one.example.com --le --wildcard```

If its getting confusing, you can stop doing any wildcard related operation unless `wildcard` is not specified.

Most of the cases mentioned in those links won't surface in practical usage. Third-level subdomains can be avoided on a test server by simply using `aplha-one.example.com` instead of `aplha.one.example.com`. 

In the production env domains are created carefully. I only know wordcamp.org as a network of sites using three level of subdomain consistently e.g. 2018.us.wordcamp.org. But new WordCamps don't get added more than 20 times a week. So again real-world scenarios are easier to deal with.

**Comment by rahul286** [comment]
@mbtamuli Maybe you can rewrite the whole spec https://github.com/EasyEngine/site-command/issues/77#issuecomment-405237811 and then I can proofread it to iron out any difference in our understanding.

**Comment by kirtangajjar** [comment]
> generate a single domain normal cert for aplha.one.example.com

AFAIK we can't use two certs for serving site under same virtualhost. We *might* need to generate a SAN cert(we're already doing this for wildcard)

**Comment by rahul286** [comment]
General Use-cases wildcard
==========================

1. I want to setup wildcard for current domains and subdomain underneath 

```
ee site create example.com --ssl=le --wildcard
```
Above command covers...
- example.com ✅
- *.example.com ✅ (one subdomain level)
- foo.example.com ✅
- bar.foo.example.com ❌ (LE issue https://community.letsencrypt.org/t/third-fourth-etc-level-domains-and-wildcards/56035/)

2. I want to setup wildcard for current subdomains and sub-subdomain underneath  

```
ee site create foo.example.com --ssl=le --wildcard
```

Above command covers...
- foo.example.com ✅
- *.foo.example.com ✅ (one subdomain level)
- bar.foo.example.com ✅
- woo.bar.foo.example.com ❌ (LE issue https://community.letsencrypt.org/t/third-fourth-etc-level-domains-and-wildcards/56035/)


Edge cases wildcard
=====================

I want to create a new subdomain (no ssl, ignore parents wildcard SSL)

```
ee site create store.example.com
```

*Note:* EE wont force parents SSL on separately created new child sites.


I want to create a new subdomain, using my parent's SSL

```
ee site create store.example.com --ssl=inherit 
```
EE will apply parent's SSL to this domain, if parent has a wildcard SSL
If parent doesn't have wildcard SSL, then display warning.
Then user can either use following commands or remove `--ssl` argument


I want to create a new subdomain, with new SSL.

```
ee site create store.example.com --ssl=le
```

I want to create a new subdomain, with new SSL, with new wildcard chain 

```
ee site create store.example.com --ssl=le --wildcard
```


--wildcard flag 
========

```
--wildcard it is a binary flag. If passed, it will add *.example.com to the request.
```

**Comment by rahulsprajapati** [comment]
Closing this issue: PR merged https://github.com/EasyEngine/easyengine/pull/1171
